version: "3.3"

services: 
  falco-sidekick:
    environment:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FALCO_SRC_PATH=falco_src
    volumes:
      - ./config.yaml:/etc/falcosidekick/config.yaml:z
    ports: 
      - 2801:2801
