version: "3.3"

services: 
  falco-sidekick:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FALCO_SRC_PATH=falco_src
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports: 
      - 2801:2801
